
export const SECTORS = [
  "Medicine",
  "City Planning",
  "Manufacturing",
  "Agriculture",
  "Education",
  "Deep-sea Exploration",
  "Space Logistics",
  "Mental Health",
  "Waste Management",
  "Public Transportation",
  "Criminal Justice",
  "Journalism",
  "Creative Arts",
  "Energy Production",
  "Water Conservation",
  "Emergency Response",
  "Supply Chain Management",
  "Environmental Protection",
  "Aviation",
  "Social Governance",
  "Hospitality",
  "Cybersecurity",
  "Architecture",
  "Sports Science",
  "Oceanography",
  "Eldercare",
  "Fashion Design",
  "Retail Commerce",
  "Renewable Energy",
  "Music Production",
  "Legal Services",
  "Telecommunications",
  "Wildlife Conservation",
  "Archeology",
  "Disaster Recovery",
  "Urban Farming",
  "Financial Services",
  "Micro-logistics",
  "Space Tourism",
  "Automotive Engineering",
  "Capitalism",
  "Socialism",
  "Academia",
  "Luxury Goods",
  "Democracy",
  "Literature",
  "Video games",
  "Computers",
  "Housing",
  "Childcare",
  "Food Science",
  "Marine Biology",
  "Pharmaceuticals",
  "Insurance",
  "Mining",
  "Forestry",
  "Broadcasting",
  "Diplomacy",
  "Pet Care",
  "Fitness Industry",
  "Interior Design",
  "Film Production",
  "Podcasting",
  "E-commerce",
  "Dating",
  "Personal Finance",
  "Climate Science",
  "Genetics",
  "Neuroscience",
  "Sleep Research",
  "Nutrition",
  "Veterinary Care",
  "Dentistry",
  "Optometry",
  "Cosmetics",
  "Brewing",
  "Winemaking",
  "Coffee Industry",
  "Textiles",
  "Ceramics",
  "Furniture Design",
  "Landscaping",
  "Event Planning",
  "Wedding Industry",
  "Funeral Services",
  "Human Resources",
  "Recruitment",
  "Coworking",
  "Freelancing",
  "Gig Economy",
  "Philanthropy",
  "Volunteering",
  "Museums",
  "Libraries",
  "Theme Parks",
  "Esports",
  "Board Games",
  "Toy Industry",
  "Parenting"
];

export const TECHNOLOGIES = [
  "Artificial Intelligence",
  "Nanotechnology",
  "Nuclear Fusion",
  "The Metaverse",
  "Swarm Robotics",
  "Quantum Computing",
  "Biometric Cryptography",
  "CRISPR Gene Editing",
  "Autonomous Vehicle Networks",
  "Next-gen Solid State Batteries",
  "Decentralized Web Architectures",
  "Brain-Computer Interfaces",
  "3D Bioprinting",
  "Carbon Capture Systems",
  "Synthetic Biology",
  "Graphene-based Superconductors",
  "Holistic Sensor Networks",
  "Generative Design Algorithms",
  "Edge Computing",
  "Smart Dust",
  "Hyperloop Transport",
  "Modular Nuclear Reactors",
  "Wireless Energy Transfer",
  "Augmented Reality HUDs",
  "Molecular Engineering",
  "Advanced Polymer Recycling",
  "Haptic Feedback Suits",
  "Regenerative Medicine",
  "Deep Space Propulsion",
  "Biomorphic Robotics",
  "Lab-grown Materials",
  "Vertical Farming Robotics",
  "Atmospheric Water Generators",
  "Personalized Genomic Medicine",
  "Optogenetics",
  "Bio-digital Convergence",
  "Zero-knowledge Proofs",
  "Neuromorphic Computing",
  "6G Connectivity",
  "Digital Twin Simulation",
  "AI Agents",
  "World Models",
  "Photonic Computing",
  "Self-healing Materials",
  "Liquid Metal Robotics",
  "Programmable Matter",
  "DNA Data Storage",
  "Quantum Cryptography",
  "Neural Lace Technology",
  "Exoskeletons",
  "Smart Textiles",
  "Biodegradable Electronics",
  "Piezoelectric Energy Harvesting",
  "Holographic Displays",
  "Spatial Computing",
  "Voice Synthesis",
  "Emotion Recognition AI",
  "Predictive Analytics",
  "Federated Learning",
  "Homomorphic Encryption",
  "Mesh Networks",
  "Low-Earth Orbit Satellites",
  "Drone Swarms",
  "Microfluidics",
  "Organ-on-a-Chip",
  "Cultured Meat",
  "Precision Fermentation",
  "Mycelium Materials",
  "Algae Bioreactors",
  "Desalination Tech",
  "Hydrogen Fuel Cells",
  "Perovskite Solar Cells",
  "Tidal Energy Systems",
  "Geothermal Drilling",
  "Plasma Gasification",
  "Additive Manufacturing",
  "Robotic Process Automation",
  "Computer Vision",
  "Natural Language Processing",
  "Reinforcement Learning",
  "Generative AI",
  "Embodied AI",
  "Ambient Computing",
  "Wearable Biosensors",
  "Smart Contact Lenses",
  "Implantable Devices",
  "Telemedicine Platforms",
  "Digital Therapeutics",
  "Longevity Research",
  "Cryopreservation"
];
